config/routes.rb
  Gloced::Application.routes.draw do
    constraints :subdomain => 'api', :format => :json do
      root :to => "pages#index"
      
      
      devise_for :users 
      devise_scope :user do
        get "/login" => "devise/sessions#new", :as => :new_user_session , :defaults => { :format => 'json' }
        post "/login" => "devise/sessions#create", :as => :new_user_session , :defaults => { :format => 'json' }

        match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

        get "/register" => "devise/registrations#new", :as => :new_user_registration 

        get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

        match "/confirm" => "devise/sessions#new", :as => :confirm 

      end
      
      match "tokens" => 'tokens#create', :via => :post
      match "tokens/:token" => 'tokens#destroy', :via => :delete
      get "/venues" => "venues#index", :as => :venues, :defaults => { :format => 'json' }
      get "/venues/:id" => "venues#show", :as => :venue, :defaults => { :format => 'json' }
      get "/events" => "events#list", :as => :events, :defaults => { :format => 'json' }
      get "/events/tag/:id" => "events#tag", :as => :taggedevents, :defaults => { :format => 'json' }
      get ':id/venues' => 'users#venues', :as => :uservenues, :defaults => { :format => 'json' }
       get ':id/events' => 'users#events', :as => :userevents, :defaults => { :format => 'json' }
       get ':id/following' => 'users#following', :as => :following, :defaults => { :format => 'json' }
       get ':id/followers' => 'users#followers', :as => :followers, :defaults => { :format => 'json' }
       get ':id' => 'users#show', :defaults => { :format => 'json' }
    end
        root :to => "pages#index"
       get "about" => 'pages#about'
       get "help" => 'pages#help'
       get "terms" => 'pages#terms'
       get "jobs" => 'pages#jobs'
       get "business" => 'pages#business'
       get "privacy" => 'pages#privacy'
       get "media" => 'pages#media'
       get "dev" => 'pages#dev'
       get "blog" => 'pages#blog'

       get "settings" => 'settings#profile'
       get "settings/account"
       get "settings/profile"

       get 'settings/password'
       put 'settings/password' => 'settings#update_password', :as => :update_password
       get "settings/notifications"

       put "settings/avatar_upload"
       put "settings/deactivate_me", :as => :deactivate_me

       devise_for :users 
       devise_scope :user do

         get "/login" => "devise/sessions#new", :as => :new_user_session 

         match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

         get "/register" => "devise/registrations#new", :as => :new_user_registration 

         get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

         match "/confirm" => "devise/sessions#new", :as => :confirm 

       end
       resources :relationships, :only => [:create, :destroy]

       get "/venues/list" => "venues#list", :as => :venues_list

       resources :venues

       get "/events/tag/:id" => "events#tag", :as => :event_tags 
       get "/events/list" => "events#list"
       get "/events/mylist" => "events#mylist"
       get "/events/mygrid" => "events#mygrid"
       get "/events/all" => "events#index"
       
       resources :events

       resources :users, :only => [:show, :update]

       get ':id/venues' => 'users#venues', :as => :uservenues
       get ':id/events' => 'users#events', :as => :userevents
       get ':id/following' => 'users#following', :as => :following
       get ':id/followers' => 'users#followers', :as => :followers
       match ':id' => 'users#show'

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
    devise :database_authenticatable, :recoverable, :rememberable, :registerable, :trackable, :validatable, :authentication_keys => [:login]
   
  has_attached_file :avatar, :styles => { :large => "600x600>", :medium => "310x310>", :thumb => "100x100#", :minithumb => "50x50#" },       
           :url => "/:attachment/:id/:style/:hash.:extension",
           :path => ":rails_root/public/:attachment/:id/:style/:hash.:extension",
           :hash_secret => "longSecretString",
           :default_url => '/avatars/:style/missing.png'
           
   validates_attachment_size :avatar, :less_than => 5.megabytes
   validates_attachment_content_type :avatar, :content_type => ['image/jpeg', 'image/png']       
  # Setup accessible (or protected) attributes for your model
  attr_accessible :firstName, :lastName, :about, :city, :state, :country, :places, :avatar,:site_u_r_l, :login, :email, :password, :password_confirmation, :remember_me ,:username, :language, :timezone
 
  attr_accessor :login
  
 
  has_many :relationships, :dependent => :destroy,
                           :foreign_key => "follower_id"
  has_many :reverse_relationships, :dependent => :destroy,
                                   :foreign_key => "followed_id",
                                   :class_name => "Relationship"

  has_many :following, :through => :relationships, :source => :followed
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_many :venues
  has_many :events
  
  def confirm!
    welcome_message
    super
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end

  def followed
    relationships.find_by_following_id(current_user.id)
  end

  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end

  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.strip.downcase }]).first
  end
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end 
  def to_param
    username
  end
  def cropping?
    !crop_x.blank? && !crop_y.blank? && !crop_w.blank? && !crop_h.blank?
  end
  
  def avatar_geometry(style = :original)
    @geometry ||= {}
    @geometry[style] ||= Paperclip::Geometry.from_file(avatar.path(style))
  end
  
  private
  
  def welcome_message
     UserMailer.welcome_message(self).deliver
  end
  
  def reprocess_avatar
    avatar.reprocess!
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!, :except => [:create, :index]    
  before_filter :current_user, :only => [:edit, :update]

   def index
    @user = User.find_by_email(params[:email]) || not_found
    
   end

  # GET /users/1
  # GET /users/1.json
  def show
    if params[:id] != current_user.username
       @user = User.find_by_username(params[:id]) || not_found
     else
       @user = current_user || not_found
     end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
  def me
    @user = current_user
    
  end

  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by_username(params[:id]) || not_found
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find_by_username(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to :back, notice: 'User was successfully updated.' }
      else
        format.html { redirect_to :back }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find_by_username(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :ok }
    end
  end
  
#  def achievements
#    @user = User.find_by_username(params[:id])
#    @users = @user.following
#   end

  def events
     @user = User.find_by_username(params[:id])
     @events = @user.events
     respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @events }
     end
  end
  def venues
     @user = User.find_by_username(params[:id])
     @venues = @user.venues
     respond_to do |format|
       format.html # show.html.erb
       format.json { render json: @venues }
     end
  end
  
  def following
      @user = User.find_by_username(params[:id])
      @users = @user.following
      render 'show_following'
      respond_to do |format|
        format.json { render json: @users }
      end
  end
  
  def followers
    @user = User.find_by_username(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_user=(user)
    @current_user = user
  end
  
  def current_user?(user)
    user == current_user
  end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.relationships.
                          build(:followed_id => @user.id),
                          :remote => true) do |f| %>
  <%= f.hidden_field :followed_id %>
  <%= f.submit "Follow", :class =>'button follow-button selected' %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
    <% if current_user.following?(@user) %>
      <%= render 'users/unfollow' %>
    <% else %>
      <%= render 'users/follow' %>
    <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<script>
$(function() {
	$( "#user_city" ).autocomplete({
		source: function( request, response ) {
			$.ajax({
				url: "http://ws.geonames.org/searchJSON",
				dataType: "jsonp",
				data: {
					featureClass: "P",
					style: "full",
					maxRows: 5,
					name_startsWith: request.term
				},
				success: function( data ) {
					response( $.map( data.geonames, function( item ) {
						return {
							label: item.name + (item.adminName1 ? ", " + item.adminName1 : "") + ", " + item.countryName,
							value: item.name
						}
					}));
				}
			});
		},
		minLength: 2,
		open: function() {
			$( this ).removeClass( "ui-corner-all" ).addClass( "ui-corner-top" );
		},
		close: function() {
			$( this ).removeClass( "ui-corner-top" ).addClass( "ui-corner-all" );
		}
	});
});
</script>

	 <div class="twoofthree padder">
		    <aside class="settings right"> <a class="block" title="Edit" href="<%= edit_user_path(@user) %>"></a></aside>
<%= form_for(@user,:html => {:multipart => true} ) do |f| %>
   <article>
	    <div class="profile_text">
		 			<div class="holder">
	         <h3 class="fkey">First Name</h2>
	         <div class="val"><%= f.text_field :firstName %></div>
	       </div>
				 <div class="holder">
		         <h3 class="fkey">Last Name</h2>
		         <div class="val"><%= f.text_field :lastName %></div>
		       </div> 
		 			<div class="holder">
	         <h3 class="fkey">Email</h2>
	         <div class="val"><%= f.text_field :email %></div>
	       </div>
		 			<div class="holder">
	         <h3 class="fkey">About</h2>
	         <div class="val"><%= f.text_field :about,:size=>"30", :maxlength=>"200"%></div>
	       </div>
		 			<div class="holder">
	         <h3 class="fkey">City</h2>
	         <div class="val"><%= f.text_field :city %></div>
	       </div>
	       <div class="holder">
	         <h3 class="fkey">Places Visited</h2>
	         <div class="val"><%= f.text_field :places %></div>
	       </div>
			 <div class="holder">
			   <h3 class="key"></h2>
        <div class="val">  <%= f.submit :class =>" button" %></div>
			  </div></div>
	 </article>
 <% end %>

	    </article>
	  </div>
	  <div class="oneofthree padder">
			 <div class="profile_text_right"> 
				<div id="uploads"> <%#= render :partial => @user.uploads %>
				</div>	<%= image_tag @user.avatar.url(:medium) %>
				
				<%= form_for @user, :url => user_path, :html => { :multipart => true } do |form| %>
			  <%= form.file_field :avatar %>
			  <%= form.submit :class =>" button" %>
				<% end %>
			</div>
	</div>
	<div class="map" style="background: url(//maps-api-ssl.google.com/maps/api/staticmap?size=485x250&amp;scale=2&amp;sensor=true&amp;language=en&amp;markers=icon:http://gloced.com/icona.png|42.3761,21.153346|42.657798,21.153346|41.33,19.82|42.00839,20.97399|42.504503,27.462959|36.903235,30.684757|44.203374,17.933407) center bottom"></div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.relationships.find_by_followed_id(@user),
             :html => { :method => :delete },
             :remote => true) do |f| %>
						  <%= f.submit "Following", :class =>'button follow-button selected' %>
<% end %>

app/views/users/achievements.html.erb
<div class="twoofthree padder">
  <article>
    <div class="followContainer">
      <% if @users.any? %>
      <% @users.each do |user| %>
      <div class="checkin outOfTown">
        <div class="avatar"><a href="/<%=user.username%>"><%=image_tag user.avatar.url(:minithumb)%> </a></div>
        <div class="content">
           <h4> <strong><a href="/<%=user.username%>"><%= user.firstName %> s<%= user.lastName %></a></strong> <%= user.city %><%= unless user.country.blank?
	 					", #{user.country}" end%></h4>
          <p class="metadata"> <%= user.about %> </p>
        </div>
        <div style="clear: both;"> </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </article>
</div>
<div class="oneofthree padder">
  <div class="profile_text">
  	<h1>Achievements? Really?</h1>
		<p> Some one should explain what a hell are those. Redon u there, u mad bro?<p>
</div>

app/views/users/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/events.html.erb
<div class="twoofthree padder">
  <article>
    <div class="followContainer">
      <% @events.each do |event| %>
      <div class="checkin outOfTown">
        <div class="avatar"><a href="/<%=event.slug%>"><%=image_tag event.poster.url(:minithumb)%> </a></div>
        <div class="content">
           <h4> <strong><a href="/<%=event.slug%>"><%= event.name %></a></strong> <%= event.venue.city %><%= unless event.venue.country.blank?
	 					", #{event.venue.country}" end%></h4>
          <p class="metadata"> <%= event.description %> </p>
        </div>
        <div style="clear: both;"><%= link_to image_tag(event.venue.logo.url(:minithumb), :size => "30x30", :style => "float:right; bottom: 10px; position: absolute;right:10px", :alt => "#{event.venue.name}"), venue_path(event.venue.slug) %></div>
      </div>
      <% end %>
    </div>
  </article>
</div>
<div class="oneofthree padder">
  <div class="profile_text">
  	<h1>Venue Listing?</h1>
		<p> Some one should explain what a hell are those. Redon u there, u mad bro?<p>
</div>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Email</th>
    <th>About</th>
    <th>City</th>
    <th>Places</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.firstName %></td>
    <td><%= user.lastName %></td>
    <td><%= user.email %></td>
    <td><%= truncate(user.about, :length => 40)  %></td>
    <td><%= user.city %></td>
    <td><%= user.places %></td>
    <td><%= user.admin %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
 <div class="twoofthree padder">
				   <article>
    <div class="profile_text">
	 			<div class="holder">
         <h3 class="key">Full Name</h2>
         <div class="val"><%= @user.firstName %> <%= @user.lastName %></div>
       </div>
	 			<div class="holder">
         <h3 class="key">Email</h2>
         <div class="val"><%= @user.email %></div>
       </div>
	 			<div class="holder">
         <h3 class="key">About</h2>
         <div class="val"><%= @user.about %></div>
       </div>
	 			<div class="holder">
         <h3 class="key">City</h2>
         <div class="val"><%= @user.city %></div>
       </div>
       <div class="holder">
         <h3 class="key">Places Visited</h2>
         <div class="val">
        
           <ul class="bK a-l-k">
             <li class="Uk dK" title="Tirana, Albania">
               <div class="adr"><%= @user.places %>
							  </div>
             </li>
           </ul>
         </div>
       </div>
    </div>
 </article>

    </article>
  </div>
  <div class="oneofthree padder">
		 <div class="profile_text_right">  
	    <div class="avatar"> <%= image_tag @user.avatar.url(:medium) %> </div>
				</div>
  	  <%= render 'shared/stats' %>
</div>
<div class="map" style="background: url(//maps-api-ssl.google.com/maps/api/staticmap?size=485x250&amp;scale=2&amp;sensor=true&amp;language=en&amp;markers=icon:http://gloced.com/icona.png|42.3761,21.153346|42.657798,21.153346|41.33,19.82|42.00839,20.97399|42.504503,27.462959|36.903235,30.684757|44.203374,17.933407) center bottom"></div>

app/views/users/show_follower.html.erb
<div class="twoofthree padder">
  <article>
    <div class="followContainer">
      <% if @users.any? %>
      <% @users.each do |user| %>
      <div class="checkin outOfTown">
        <div class="avatar"><a href="/<%=user.username%>"><%=image_tag user.avatar.url(:minithumb)%> </a></div>
        <div class="content">
          <div class="hoverControls"> 
				    <% if current_user.following?(@user) %>
				      <%= render 'users/unfollow' %>
				    <% else %>
				      <%= render 'users/follow' %>
				    <% end %>
					</div>
          <h4> <strong><a href="/<%=user.username%>"><%= user.firstName %> <%= user.lastName %></a></strong> <%= user.city %><%= unless user.country.blank?
	 					", #{user.country}" end%></h4>
          <p class="metadata"> <%= user.about %> </p>
        </div>
        <div style="clear: both;"> </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </article>
  </article>
</div>
<div class="oneofthree padder">
  <div class="profile_text_right">
    <div class="avatar"> <%= image_tag @user.avatar.url(:medium) %> </div>
  </div>
  <%= render 'shared/stats' %> 
</div>

app/views/users/show_following.html.erb
<div class="twoofthree padder">
  <article>
    <div class="followContainer">
      <% if @users.any? %>
      <% @users.each do |user| %>
      <div class="checkin outOfTown">
        <div class="avatar"><a href="/<%=user.username%>"><%=image_tag user.avatar.url(:minithumb)%> </a></div>
        <div class="content">
          <div class="hoverControls"> 
				    <% if current_user.following?(@user) %>
				      <%= render 'users/unfollow' %>
				    <% else %>
				      <%= render 'users/follow' %>
				    <% end %>
					</div>
          <h4> <strong><a href="/<%= user.username %>"><%= user.firstName %> <%= user.lastName %></a></strong> <%= user.city %><%= unless user.country.blank?
	 					", #{user.country}" end%></h4>
          <p class="metadata"> <%= user.about %> </p>
        </div>
        <div style="clear: both;"> </div>
      </div>
      <% end %>
      <% end %>
    </div>
  </article>
  </article>
</div>
<div class="oneofthree padder">
  <div class="profile_text_right">
    <div class="avatar"> <%= image_tag @user.avatar.url(:medium) %> </div>
  </div>
  <%= render 'shared/stats' %> </div>

app/views/users/venues.html.erb
<div class="twoofthree padder">
  <article>
    <div class="followContainer">
      <% @venues.each do |venue| %>
      <div class="checkin outOfTown">
        <div class="avatar"><a href="/venues/<%=venue.slug%>"><%=image_tag venue.logo.url(:minithumb)%> </a></div>
        <div class="content">
           <h4> <strong><a href="/venues/<%=venue.slug%>"><%= venue.name %></a></strong> <%= venue.city %><%= unless venue.country.blank?
	 					", #{venue.country}" end%></h4>
	          <p class="metadata"> <%= venue.address %> </p>
	          <p class="metadata"> <%= venue.website %> </p>
	          <p class="metadata"> <%= venue.twitter %> </p>
	          <p class="metadata"> <%= venue.fb %> </p>
        </div>
        <div style="clear: both;"></div>
      </div>
      <% end %>
    </div>
  </article>
</div>
<div class="oneofthree padder">
  <div class="profile_text">
  	<h1>venues Listing?</h1>
		<p> Some one should explain what a hell are those. Redon u there, u mad bro?<p>
</div>