config/routes.rb
  Gloced::Application.routes.draw do
    constraints :subdomain => 'api', :format => :json do
      root :to => "pages#index"
      
      
      devise_for :users 
      devise_scope :user do
        get "/login" => "devise/sessions#new", :as => :new_user_session , :defaults => { :format => 'json' }
        post "/login" => "devise/sessions#create", :as => :new_user_session , :defaults => { :format => 'json' }

        match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

        get "/register" => "devise/registrations#new", :as => :new_user_registration 

        get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

        match "/confirm" => "devise/sessions#new", :as => :confirm 

      end
      
      match "tokens" => 'tokens#create', :via => :post
      match "tokens/:token" => 'tokens#destroy', :via => :delete
      get "/venues" => "venues#index", :as => :venues, :defaults => { :format => 'json' }
      get "/venues/:id" => "venues#show", :as => :venue, :defaults => { :format => 'json' }
      get "/events" => "events#list", :as => :events, :defaults => { :format => 'json' }
      get "/events/tag/:id" => "events#tag", :as => :taggedevents, :defaults => { :format => 'json' }
      get ':id/venues' => 'users#venues', :as => :uservenues, :defaults => { :format => 'json' }
       get ':id/events' => 'users#events', :as => :userevents, :defaults => { :format => 'json' }
       get ':id/following' => 'users#following', :as => :following, :defaults => { :format => 'json' }
       get ':id/followers' => 'users#followers', :as => :followers, :defaults => { :format => 'json' }
       get ':id' => 'users#show', :defaults => { :format => 'json' }
    end
        root :to => "pages#index"
       get "about" => 'pages#about'
       get "help" => 'pages#help'
       get "terms" => 'pages#terms'
       get "jobs" => 'pages#jobs'
       get "business" => 'pages#business'
       get "privacy" => 'pages#privacy'
       get "media" => 'pages#media'
       get "dev" => 'pages#dev'
       get "blog" => 'pages#blog'

       get "settings" => 'settings#profile'
       get "settings/account"
       get "settings/profile"

       get 'settings/password'
       put 'settings/password' => 'settings#update_password', :as => :update_password
       get "settings/notifications"

       put "settings/avatar_upload"
       put "settings/deactivate_me", :as => :deactivate_me

       devise_for :users 
       devise_scope :user do

         get "/login" => "devise/sessions#new", :as => :new_user_session 

         match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

         get "/register" => "devise/registrations#new", :as => :new_user_registration 

         get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

         match "/confirm" => "devise/sessions#new", :as => :confirm 

       end
       resources :relationships, :only => [:create, :destroy]

       get "/venues/list" => "venues#list", :as => :venues_list

       resources :venues

       get "/events/tag/:id" => "events#tag", :as => :event_tags 
       get "/events/list" => "events#list"
       get "/events/mylist" => "events#mylist"
       get "/events/mygrid" => "events#mygrid"
       get "/events/all" => "events#index"
       
       resources :events

       resources :users, :only => [:show, :update]

       get ':id/venues' => 'users#venues', :as => :uservenues
       get ':id/events' => 'users#events', :as => :userevents
       get ':id/following' => 'users#following', :as => :following
       get ':id/followers' => 'users#followers', :as => :followers
       match ':id' => 'users#show'

  end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(object.errors.count, "error") %>
      prohibited this <%= object.class.to_s.underscore.humanize.downcase %>
      from being saved:
    </h2>
    <p>There were problems with the following fields:</p>
    <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
  
<% end %>

app/views/shared/_event_form.html.erb
<%= form_for(@event) do |f| %>
  <%= render 'shared/error_messages', :object => f.object %>
  <div class="field">
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <table class="events" summary="Status feed">
    <%= render :partial => 'shared/feed_item', :collection => @feed_items %>
  </table>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<tr>
  <td class="gravatar">
    <%= link_to gravatar_for(feed_item.user), feed_item.user %>
  </td>
  <td class="event">
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="content"><%= wrap(feed_item.content) %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user?(feed_item.user) %>
    <td>
      <%= link_to "delete", feed_item, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => feed_item.content %>
    </td>
  <% end %>
</tr>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>

<ul class="profile-stats group">
  <li> <a href="/flakerimi/events"> <strong>a<%#= @user.events.count %></strong> <span>Events</span> </a> </li>
  <li> <a href="/flakerimi/venues"> <strong>2</strong> <span>Venues</span> </a> </li>
  <li> <a href="/flakerimi/achievements"> <strong>0</strong> <span>Achievements</span> </a> </li>
  <li> <a href="<%= followers_path(@user) %>"> <strong><%= @user.followers.count %></strong> <span>Followers</span> </a> </li>
  <li> <a href="<%= following_path(@user) %>"> <strong class="followee-count"><%= @user.following.count %></strong> <span>Following</span> </a> </li>
   <li> <a href="#"> <strong><%= @user.created_at.strftime("%b %Y") %></strong> <span>Member Since</span> </a> </li>
</ul>

app/views/shared/_upload.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
a

app/views/shared/_user_info.html.erb
<div class="user_info">
  <a href="<%= user_path(current_user) %>">
    <%= gravatar_for current_user, :size => 30 %>
    <span class="user_name">
      <%= current_user.name %>
    </span>
    <span class="events">
      <%= pluralize(current_user.events.count, "event") %>
    </span>
  </a>
</div>