config/routes.rb
  Gloced::Application.routes.draw do
    constraints :subdomain => 'api', :format => :json do
      root :to => "pages#index"
      
      
      devise_for :users 
      devise_scope :user do
        get "/login" => "devise/sessions#new", :as => :new_user_session , :defaults => { :format => 'json' }
        post "/login" => "devise/sessions#create", :as => :new_user_session , :defaults => { :format => 'json' }

        match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

        get "/register" => "devise/registrations#new", :as => :new_user_registration 

        get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

        match "/confirm" => "devise/sessions#new", :as => :confirm 

      end
      
      match "tokens" => 'tokens#create', :via => :post
      match "tokens/:token" => 'tokens#destroy', :via => :delete
      get "/venues" => "venues#index", :as => :venues, :defaults => { :format => 'json' }
      get "/venues/:id" => "venues#show", :as => :venue, :defaults => { :format => 'json' }
      get "/events" => "events#list", :as => :events, :defaults => { :format => 'json' }
      get "/events/tag/:id" => "events#tag", :as => :taggedevents, :defaults => { :format => 'json' }
      get ':id/venues' => 'users#venues', :as => :uservenues, :defaults => { :format => 'json' }
       get ':id/events' => 'users#events', :as => :userevents, :defaults => { :format => 'json' }
       get ':id/following' => 'users#following', :as => :following, :defaults => { :format => 'json' }
       get ':id/followers' => 'users#followers', :as => :followers, :defaults => { :format => 'json' }
       get ':id' => 'users#show', :defaults => { :format => 'json' }
    end
        root :to => "pages#index"
       get "about" => 'pages#about'
       get "help" => 'pages#help'
       get "terms" => 'pages#terms'
       get "jobs" => 'pages#jobs'
       get "business" => 'pages#business'
       get "privacy" => 'pages#privacy'
       get "media" => 'pages#media'
       get "dev" => 'pages#dev'
       get "blog" => 'pages#blog'

       get "settings" => 'settings#profile'
       get "settings/account"
       get "settings/profile"

       get 'settings/password'
       put 'settings/password' => 'settings#update_password', :as => :update_password
       get "settings/notifications"

       put "settings/avatar_upload"
       put "settings/deactivate_me", :as => :deactivate_me

       devise_for :users 
       devise_scope :user do

         get "/login" => "devise/sessions#new", :as => :new_user_session 

         match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

         get "/register" => "devise/registrations#new", :as => :new_user_registration 

         get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

         match "/confirm" => "devise/sessions#new", :as => :confirm 

       end
       resources :relationships, :only => [:create, :destroy]

       get "/venues/list" => "venues#list", :as => :venues_list

       resources :venues

       get "/events/tag/:id" => "events#tag", :as => :event_tags 
       get "/events/list" => "events#list"
       get "/events/mylist" => "events#mylist"
       get "/events/mygrid" => "events#mygrid"
       get "/events/all" => "events#index"
       
       resources :events

       resources :users, :only => [:show, :update]

       get ':id/venues' => 'users#venues', :as => :uservenues
       get ':id/events' => 'users#events', :as => :userevents
       get ':id/following' => 'users#following', :as => :following
       get ':id/followers' => 'users#followers', :as => :followers
       match ':id' => 'users#show'

  end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :user_id, :venue_id, :name, :description, :tag_list, :start_time, :end_time, :poster
  acts_as_taggable_on
  acts_as_taggable_on :tags
  belongs_to :user 
  belongs_to :venue 
  self.per_page = 3
  has_attached_file :poster, :processors => [:watermark],
                 :styles => { 
                             :medium => "310", 
                             :thumb => "150", 
                             :minithumb => {
                               :geometry => "50",
                               :format => 'png'
                               }
                             },       
          :url => "/events/:attachment/:id/:style/:hash.:extension",
          :path => ":rails_root/public/events/:attachment/:id/:style/:hash.:extension",
          :hash_secret => "longSecretString",
          :default_url => "/events/:attachment/:style/missing.png"
          
  validates_attachment_size :poster, :less_than => 1.megabytes
  
  before_save :create_slug
  
  def to_param
    slug
  end
  
  def poster_url
      poster.url(:minithumb)
  end

  def create_slug
    self.slug =  [self.id, self.name.parameterize].join("-")
  end
  
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @events = Event.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => Event.per_page)
     respond_to do |format|
      format.html # index.html.erb
      format.json  { render :json => @events.to_json(:methods => [:poster_url])}
      format.js  
   end
  end
  def list
    @events = Event.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => Event.per_page)

     respond_to do |format|
       format.html # index.html.erb
      # format.json { render json: @events }
      format.json  { render :json => @events.to_json(:methods => [:poster_url])}  
       format.js        
     end
   end

   def mygrid
     @events = Event.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => Event.per_page).order('id DESC')
      respond_to do |format|
       format.html # index.html.erb
       format.json  { render :json => @events.to_json(:methods => [:poster_url])}
       format.js  
    end
   end
   def mylist
     @events = Event.where(:user_id => current_user.id).paginate(:page => params[:page], :per_page => Event.per_page)

      respond_to do |format|
        format.html # index.html.erb
       # format.json { render json: @events }
       format.json  { render :json => @events.to_json(:methods => [:poster_url])}  
        format.js        
      end
    end

   def tag
    @events = Event.tagged_with(params[:id])

    respond_to do |format|
      format.html # index.html.erb
        format.json  { render :json => @events.to_json(:methods => [:poster_url])}
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
     @event = Event.find_by_slug(params[:id])
     #@venue = Venue.find :all, :conditions => ["user_id", current_user.id]

    respond_to do |format|
      format.html # show.html.erb
        format.json  { render :json => @events.to_json(:methods => [:poster_url])}
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    @venue = Venue.find :all, :conditions => ["user_id", current_user.id]
    respond_to do |format|
      format.html # new.html.erb
        format.json  { render :json => @events.to_json(:methods => [:poster_url])}
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find_by_slug(params[:id])
    @venue = Venue.find :all, :conditions => ["user_id", current_user.id]
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find_by_slug(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/!index.html.erb
<% 	@object = Event.find(:all, :conditions => ['user_id = ?', current_user.id]).collect {|p| [ p.name, p.id ] }
	if @object.empty? %>
		<section id="events" class="twoofthree padder">
			<article>
		<h2>You haven't created any Event.<br> Why not <a href="/events/new" style="color:#F66">create</a> one first!</h2><br>
		<img src="/images/why.jpeg">
		</article></section>
	<% else %>
	<section id="events">
		
		
		<% @events.each_slice(3) do |slice| -%>
		  <div class="row">
		    <% slice.each do |event| -%>
			<div class="oneofthree padder">
			  <article class="event-block">
			    <div class="holder">
			      <aside class="settings right"> <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a> <%=link_to "", event, confirm:
			                                'Are you sure you want to delete it? There is no UNDO, plus all history of this event will be gone, FOREVER. So?',:class=>'delete', method: :delete %></aside>
			      <div class="pic-thumb"> <%=image_tag event.poster.url(:thumb) %>
			        <div class="venue-icon"> <%=image_tag event.venue.logo.url(:minithumb) %> </div>
			        <div class="sharer">
			          <ul>
			            <li> <a href="/events/top" class=""><img src="/images/icons/glocit.png"  alt="Gloc it"></a> </li>
			            <li> <a href="/events/top" class=""><img src="/images/icons/attend.png" alt="Attend"></a> </li>
			            <li> <a href="/badges/all" class=""><img src="/images/icons/share.png" alt="Share"></a> </li>
			            <li> <a href="/events/my" class=""><img src="/images/icons/flag.png" alt="Flag"></a> </li>
			          </ul>
			        </div>
			      </div>
			      <div class="date"> 
							<span class="day"> <%=event.start_time.strftime( "%A") %> </span> 
							<span class="daydate"> <%=event.start_time.strftime( "%m") %> </span> 
							<span class="month"><%=event.start_time.strftime( "%b") %> <br> <%=event.start_time.strftime( "%Y") %> </span>
			 				<span class="hour"> <%=event.start_time.strftime( "%H:%M") %>h</span>
			        <ul class="tags">
			          <% event.tag_list.each do |tag| -%>
			          <li> <%=link_to tag, event_tags_path( "#{tag}") -%> </li>
			          <% end %>
			        </ul>
			      </div>
			      <h1> <%=link_to event.name, event_path(event.slug) %> </h1>
			      <div class="desc"> <%=event.description %> </div>
			    </div>
			  </article>
			</div>		    <% end -%>
		  </div>
		<% end -%>
		

	</section>

	<%= will_paginate @events %>
<% end %>

app/views/events/_event.html.erb
				<li class="<% event.tag_list.each do |tag| -%>
				          <%= "#{tag}" -%> 
				          <% end %> ">
				<div class="oneofthree padder">
				  <article class="event-block">
				    <div class="holder">
				      <aside class="settings right"> <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a> <%=link_to "", event, confirm:
				                                'Are you sure you want to delete it? There is no UNDO, plus all history of this event will be gone, FOREVER. So?',:class=>'delete', method: :delete %></aside>
				      <div class="pic-thumb"> <%=image_tag event.poster.url(:thumb) %>
				        <div class="venue-icon"> <%=image_tag event.venue.logo.url(:minithumb) %> </div>
				        <div class="sharer">
				          <ul>
				            <li> <a href="/events/top" class=""><img src="/images/icons/glocit.png"  alt="Gloc it"></a> </li>
				            <li> <a href="/events/top" class=""><img src="/images/icons/attend.png" alt="Attend"></a> </li>
				            <li> <a href="/badges/all" class=""><img src="/images/icons/share.png" alt="Share"></a> </li>
				            <li> <a href="/events/my" class=""><img src="/images/icons/flag.png" alt="Flag"></a> </li>
				          </ul>
				        </div>
				      </div>
				      <div class="date"> 
								<span class="day"> <%=event.start_time.strftime( "%A") %> </span> 
								<span class="daydate"> <%=event.start_time.strftime( "%m") %> </span> 
								<span class="month"><%=event.start_time.strftime( "%b") %> <br> <%=event.start_time.strftime( "%Y") %> </span>
				 				<span class="hour"> <%=event.start_time.strftime( "%H:%M") %>h</span>
				        <ul class="tags">
				          <% event.tag_list.each do |tag| -%>
				          <li> <%=link_to tag, event_tags_path( "#{tag}") -%> </li>
				          <% end %>
				        </ul>
				      </div>
				      <h1> <%=link_to event.name, event_path(event.slug) %> </h1>
				      <div class="desc"> <%=event.description %> </div>
				    </div>
				  </article>
				</div>
			</li>

app/views/events/edit.html.erb
<%= render 'form' %>

app/views/events/index.html.erb
<% 	@object = Event.find(:all, :conditions => ['user_id = ?', current_user.id]).collect {|p| [ p.name, p.id ] }
	if @object.empty? %>
		<section id="events" class="twoofthree padder">
			<article>
		<h2>You haven't created any Event.<br> Why not <a href="/events/new" style="color:#F66">create</a> one first!</h2><br>
		<img src="/images/why.jpeg">
		</article></section>
	<% else %>
	<section id="events">
		      <ol id="filters">	
		      	<% @events.each do |event| %>

		      	   <% event.tag_list.each do |tag| -%>
				          <li data-filter="<%="#{tag}"%>"> <%= "#{tag}" -%> </li>
				          <% end %>
	<% end %>
      </ol>
      <ul id="tiles">
      		<% @events.each do |event| %>
		    	<%#= render :partial => "event", :collection => event, :as => :event %>
		    					<li class="<% event.tag_list.each do |tag| -%>
				          <%= "#{tag}" -%> 
				          <% end %> ">
				<div class="oneofthree padder">
				  <article class="event-block">
				    <div class="holder">
				      <aside class="settings right"> <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a> <%=link_to "", event, confirm:
				                                'Are you sure you want to delete it? There is no UNDO, plus all history of this event will be gone, FOREVER. So?',:class=>'delete', method: :delete %></aside>
				      <div class="pic-thumb"> <%=image_tag event.poster.url(:thumb) %>
				        <div class="venue-icon"> <%=image_tag event.venue.logo.url(:minithumb) %> </div>
				        <div class="sharer">
				          <ul>
				            <li> <a href="/events/top" class=""><img src="/images/icons/glocit.png"  alt="Gloc it"></a> </li>
				            <li> <a href="/events/top" class=""><img src="/images/icons/attend.png" alt="Attend"></a> </li>
				            <li> <a href="/badges/all" class=""><img src="/images/icons/share.png" alt="Share"></a> </li>
				            <li> <a href="/events/my" class=""><img src="/images/icons/flag.png" alt="Flag"></a> </li>
				          </ul>
				        </div>
				      </div>
				      <div class="date"> 
								<span class="day"> <%=event.start_time.strftime( "%A") %> </span> 
								<span class="daydate"> <%=event.start_time.strftime( "%m") %> </span> 
								<span class="month"><%=event.start_time.strftime( "%b") %> <br> <%=event.start_time.strftime( "%Y") %> </span>
				 				<span class="hour"> <%=event.start_time.strftime( "%H:%M") %>h</span>
				        <ul class="tags">
				          <% event.tag_list.each do |tag| -%>
				          <li> <%=link_to tag, event_tags_path( "#{tag}") -%> </li>
				          <% end %>
				        </ul>
				      </div>
				      <h1> <%=link_to event.name, event_path(event.slug) %> </h1>
				      <div class="desc"> <%=event.description %> </div>
				    </div>
				  </article>
				</div>
			</li>
		  <% end %>
		 </ul>


	</section>

	<%= will_paginate @events %>
<% end %>

app/views/events/index.js.erb
$('#tiles').append('<%= j render(@events) %>');
<% if @events.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@events) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep 1 %>

app/views/events/list.html.erb
<% 	@object = Event.find(:all, :conditions => ['user_id = ?', current_user.id]).collect {|p| [ p.name, p.id ] }
	if @object.empty? %>
		<section id="events" class="twoofthree padder">
			<article>
		<h2>You haven't created any Event.<br> Why not <a href="/events/new" style="color:#F66">create</a> one first!</h2><br>
		<img src="/images/why.jpeg">
		</article></section>
	<% else %>

<% if @events.any? %>
           <% @events.each do |event| %>
                <div class="one padder">
                    <article class="event-list">
                        <div class="holder">
													<% unless current_user?(@user) %>
													
                            <aside class="settings right">
                                <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a>
																<%=link_to "", event, confirm: 'Are you sure you want to delete it? It will be gone, FOREVER. So?',:class=>'delete', :title =>"Delete",  method: :delete %>
														</aside>
														<%= link_to image_tag(event.venue.logo.url(:minithumb), :size => "30x30", :style => "float:right; bottom: 10px; position: absolute;right:10px", :alt => "#{event.venue.name}"), venue_path(event.venue.slug) %>
														<% end %>
                            <div class="pic-thumb">
                                <%=image_tag event.poster.url(:minithumb) %>
                            </div>
                            <div class="date">
                                <span class="day">
                                    <%=event.start_time.strftime( "%A") %>
                                </span>
                                <span class="daydate">
                                    <%=event.start_time.strftime( "%m") %>
                                </span>
                                <span class="month">
                                    <%=event.start_time.strftime( "%b") %>
                                        <br>
                                        <%=event.start_time.strftime( "%Y") %>
                                </span>
                                <span class="hour">
                                    <%=event.start_time.strftime( "%H:%M") %>h</span>
                            </div>
                            <div class="row"><div class="title">
                                <%=link_to event.name, event_path(event.slug) %>
                            </div>
                            <div class="desc">
                                <%=event.description %>
                            </div>
                            <div class="navtags">
	                            <ul class="tags">
	                                <% event.tag_list.each do |tag| %>
	                                    <li>
	                                        <%=link_to tag, event_tags_path( "#{tag}")-%>
	                                    </li>
	                                <% end -%>
	                            </ul>
														</div>
                        </div>    <div class="sharer">
											        <ul>
											          <li><a href="/events/top" class=""><img src="/images/icons/glocit.png"  alt="Gloc it"></a></li>
											          <li><a href="/events/top" class=""><img src="/images/icons/attend.png" alt="Attend"></a></li>
											          <li><a href="/badges/all" class=""><img src="/images/icons/share.png" alt="Share"></a></li>
											          <li><a href="/events/my" class=""><img src="/images/icons/flag.png" alt="Flag"></a></li>
											        </ul>
											      </div>
                    </article>
                </div>
   <% end %>
<% end %>	
<%= will_paginate @events, :params => {:controller => "events",:actio =>"list",:page =>'1' } %>
<% end %>

app/views/events/mylist.html.erb
<% 	@object = Event.find(:all, :conditions => ['user_id = ?', current_user.id]).collect {|p| [ p.name, p.id ] }
	if @object.empty? %>
		<section id="events" class="twoofthree padder">
			<article>
		<h2>You haven't created any Event.<br> Why not <a href="/events/new" style="color:#F66">create</a> one first!</h2><br>
		<img src="/images/why.jpeg">
		</article></section>
	<% else %>

<% if @events.any? %>
           <% @events.each do |event| %>
                <div class="one padder">
                    <article class="event-list">
                        <div class="holder">
													<% unless current_user?(@user) %>
													
                            <aside class="settings right">
                                <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a>
																<%=link_to "", event, confirm: 'Are you sure you want to delete it? It will be gone, FOREVER. So?',:class=>'delete', :title =>"Delete",  method: :delete %>
														</aside>
														<%= link_to image_tag(event.venue.logo.url(:minithumb), :size => "30x30", :style => "float:right; bottom: 10px; position: absolute;right:10px", :alt => "#{event.venue.name}"), venue_path(event.venue.slug) %>
														<% end %>
                            <div class="pic-thumb">
                                <%=image_tag event.poster.url(:minithumb) %>
                            </div>
                            <div class="date">
                                <span class="day">
                                    <%=event.start_time.strftime( "%A") %>
                                </span>
                                <span class="daydate">
                                    <%=event.start_time.strftime( "%m") %>
                                </span>
                                <span class="month">
                                    <%=event.start_time.strftime( "%b") %>
                                        <br>
                                        <%=event.start_time.strftime( "%Y") %>
                                </span>
                                <span class="hour">
                                    <%=event.start_time.strftime( "%H:%M") %>h</span>
                            </div>
                            <div class="row"><div class="title">
                                <%=link_to event.name, event_path(event.slug) %>
                            </div>
                            <div class="desc">
                                <%=event.description %>
                            </div>
                            <div class="navtags">
	                            <ul class="tags">
	                                <% event.tag_list.each do |tag| %>
	                                    <li>
	                                        <%=link_to tag, event_tags_path( "#{tag}")-%>
	                                    </li>
	                                <% end -%>
	                            </ul>
														</div>
                        </div>    <div class="sharer">
											        <ul>
											          <li><a href="/events/top" class=""><img src="/images/icons/glocit.png"  alt="Gloc it"></a></li>
											          <li><a href="/events/top" class=""><img src="/images/icons/attend.png" alt="Attend"></a></li>
											          <li><a href="/badges/all" class=""><img src="/images/icons/share.png" alt="Share"></a></li>
											          <li><a href="/events/my" class=""><img src="/images/icons/flag.png" alt="Flag"></a></li>
											        </ul>
											      </div>
                    </article>
                </div>
   <% end %>
<% end %>	
<%= will_paginate @events %>
<% end %>

app/views/events/new.html.erb
<%= render 'form' %>

app/views/events/show.html.erb
	 <div class="twoofthree padder">
		    <aside class="settings right"> <a class="block" title="Edit" href="<%= edit_event_path(@event) %>"></a></aside>
   <article>
	    <div class="profile_text">
		 			<div class="holder">
	         <div class="val"><h1><%= @event.name %></h1></div>
	       </div>
				 <div class="holder">
		         <h3 class="key">Description</h2>
		         <div class="val"><%=  @event.description %></div>
		       </div> 
			 			<div class="holder">
		         <h3 class="key"></h2>
		         <div class="val"><%=  @event.start_time.strftime("Start on:%A | %m %B %Y %H:%M ") %> <br> <%=  @event.end_time.strftime("Ends on %A | %m %B %Y %H:%M ") %></div>
		       </div>
				</div>
	 </article>
   <article><h1>Tags</h1>
				<ul class="tags">
						<% if Event.tag_counts.length > 0 -%>
				        <% tag_cloud Event.tag_counts, %w(css1 css2 css3 css4) do |tag, css_class| -%>
				          	<li>  <%= link_to tag.name, event_tags_path("#{tag}") -%></li>
				        <% end -%>
				    <% else -%>
				        <%= content_tag :p, 'No tags' -%>
				    <% end -%>
				</ul>
		 </article>

	  </div>
	  <div class="oneofthree padder"><%= image_tag @event.poster.url(:medium) %>
	</div>
	<div id="map-canvas" class="map rounded"></div>
	<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var map;
function initialize() {
  var myLatlng = new google.maps.LatLng(<%=  @event.venue.longlat %>);
  var myOptions = {
    zoom: 14,
    center: myLatlng,
		'disableDefaultUI':true,
    mapTypeId: google.maps.MapTypeId.ROADMAP

  }
  map = new google.maps.Map(document.getElementById("map-canvas"), myOptions);

 
  var marker = new google.maps.Marker({
			icon:  "<%= @event.venue.logo.url(:minithumb) %>",
      position: myLatlng,
      map: map,
      title:"<%= @event.venue.name %>"
  });
}

      google.maps.event.addDomListener(window, 'load', initialize);

</script>

app/views/events/tag.html.erb
<% if @events.any? %>
	<% @events.each_slice(3) do |slice| %>
		<%= content_tag :div, :class => :row do %>
			<% slice.each do |event| %>
	
<div class="oneofthree padder">
  <article class="event-block">
    <div class="holder">
      <aside class="settings right"> <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a><%= link_to "", event, confirm: 'Are you sure you want to delete it? There is no UNDO, plus all history of this event will be gone, FOREVER. So?',:class =>'delete', method: :delete %></aside>
      <div class="pic-thumb"><%= image_tag event.poster.url(:thumb) %></div>
      <div class="date">

				<span class="day"><%=  event.start_time.strftime("%A") %> </span>
				<span class="daydate"><%=  event.start_time.strftime("%m") %>  </span>
				<span class="month"><%=  event.start_time.strftime("%b") %> <br>
			<%=  event.start_time.strftime("%Y") %>  </span>
				<span class="hour"><%=  event.start_time.strftime("%H:%M") %> h </span>


</div>
      <div class="sharer">
        <ul>
          <li><span class="newspaper"></span><a href="/events/top" class="">GLOC IT</a></li>
          <li class="share"><span style="left: -40px; width: 30px; "></span><a class="">SHARE</a></li>
          <li class="share"><span style="left: -40px; width: 30px; "></span><a href="/badges/all" class="">EMBED</a></li>
          <li class="share"><span style="left: -40px; width: 30px; "></span><a href="/events/my" class="">FLAG</a></li>
        </ul>
      </div>
      <h1> <%= link_to event.name, event_path(event.slug) %></h1>
      <div class="desc"><%= event.description %></div>
      <ul class="tags">
        <% event.tag_list.each do |tag| -%>
        <li> <%= link_to tag, event_tags_path("#{tag}"), -%></li>
        <% end -%>
      </ul>
    </div>
  </article>
</div>
			<% end %>
		<% end %>


<% end %>
<% end %>

app/views/events/trending.html.erb
<% 	@object = Event.find(:all, :conditions => ['user_id = ?', current_user.id]).collect {|p| [ p.name, p.id ] }
	if @object.empty? %>
		<section id="events" class="twoofthree padder">
			<article>
		<h2>You haven't created any Event.<br> Why not <a href="/events/new" style="color:#F66">create</a> one first!</h2><br>
		<img src="/images/why.jpeg">
		</article></section>
	<% else %>

<% if @events.any? %>
           <% @events.each do |event| %>
                <div class="one padder">
                    <article class="event-list">
                        <div class="holder">
													<% unless current_user?(@user) %>
													
                            <aside class="settings right">
                                <a class="block" title="Edit" href="<%= edit_event_path(event) %>"></a>
																<%=link_to "", event, confirm: 'Are you sure you want to delete it? It will be gone, FOREVER. So?',:class=>'delete', :title =>"Delete",  method: :delete %>
														</aside>
														<%= link_to image_tag(event.venue.logo.url(:minithumb), :size => "30x30", :style => "float:right; bottom: 10px; position: absolute;right:10px", :alt => "#{event.venue.name}"), venue_path(event.venue.slug) %>
														<% end %>
                            <div class="pic-thumb">
                                <%=image_tag event.poster.url(:minithumb) %>
                            </div>
                            <div class="date">
                                <span class="day">
                                    <%=event.start_time.strftime( "%A") %>
                                </span>
                                <span class="daydate">
                                    <%=event.start_time.strftime( "%m") %>
                                </span>
                                <span class="month">
                                    <%=event.start_time.strftime( "%b") %>
                                        <br>
                                        <%=event.start_time.strftime( "%Y") %>
                                </span>
                                <span class="hour">
                                    <%=event.start_time.strftime( "%H:%M") %>h</span>
                            </div>
                            <div class="row"><div class="title">
                                <%=link_to event.name, event_path(event.slug) %>
                            </div>
                            <div class="desc">
                                <%=event.description %>
                            </div>
                            <div class="navtags">
	                            <ul class="tags">
	                                <% event.tag_list.each do |tag| %>
	                                    <li>
	                                        <%=link_to tag, event_tags_path( "#{tag}")-%>
	                                    </li>
	                                <% end -%>
	                            </ul>
														</div>
                        </div>    <div class="sharer">
											        <ul>
											          <li><a href="/events/top" class=""><img src="/images/icons/glocit.png"  alt="Gloc it"></a></li>
											          <li><a href="/events/top" class=""><img src="/images/icons/attend.png" alt="Attend"></a></li>
											          <li><a href="/badges/all" class=""><img src="/images/icons/share.png" alt="Share"></a></li>
											          <li><a href="/events/my" class=""><img src="/images/icons/flag.png" alt="Flag"></a></li>
											        </ul>
											      </div>
                    </article>
                </div>
   <% end %>
<% end %>	
<%= will_paginate @events %>
<% end %>