config/routes.rb
  Gloced::Application.routes.draw do
    constraints :subdomain => 'api', :format => :json do
      root :to => "pages#index"
      
      
      devise_for :users 
      devise_scope :user do
        get "/login" => "devise/sessions#new", :as => :new_user_session , :defaults => { :format => 'json' }
        post "/login" => "devise/sessions#create", :as => :new_user_session , :defaults => { :format => 'json' }

        match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

        get "/register" => "devise/registrations#new", :as => :new_user_registration 

        get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

        match "/confirm" => "devise/sessions#new", :as => :confirm 

      end
      
      match "tokens" => 'tokens#create', :via => :post
      match "tokens/:token" => 'tokens#destroy', :via => :delete
      get "/venues" => "venues#index", :as => :venues, :defaults => { :format => 'json' }
      get "/venues/:id" => "venues#show", :as => :venue, :defaults => { :format => 'json' }
      get "/events" => "events#list", :as => :events, :defaults => { :format => 'json' }
      get "/events/tag/:id" => "events#tag", :as => :taggedevents, :defaults => { :format => 'json' }
      get ':id/venues' => 'users#venues', :as => :uservenues, :defaults => { :format => 'json' }
       get ':id/events' => 'users#events', :as => :userevents, :defaults => { :format => 'json' }
       get ':id/following' => 'users#following', :as => :following, :defaults => { :format => 'json' }
       get ':id/followers' => 'users#followers', :as => :followers, :defaults => { :format => 'json' }
       get ':id' => 'users#show', :defaults => { :format => 'json' }
    end
        root :to => "pages#index"
       get "about" => 'pages#about'
       get "help" => 'pages#help'
       get "terms" => 'pages#terms'
       get "jobs" => 'pages#jobs'
       get "business" => 'pages#business'
       get "privacy" => 'pages#privacy'
       get "media" => 'pages#media'
       get "dev" => 'pages#dev'
       get "blog" => 'pages#blog'

       get "settings" => 'settings#profile'
       get "settings/account"
       get "settings/profile"

       get 'settings/password'
       put 'settings/password' => 'settings#update_password', :as => :update_password
       get "settings/notifications"

       put "settings/avatar_upload"
       put "settings/deactivate_me", :as => :deactivate_me

       devise_for :users 
       devise_scope :user do

         get "/login" => "devise/sessions#new", :as => :new_user_session 

         match "/logout" => "devise/sessions#destroy", :as => :destroy_user_session 

         get "/register" => "devise/registrations#new", :as => :new_user_registration 

         get "/forget-password" => "devise/passwords#new", :as => :new_user_password 

         match "/confirm" => "devise/sessions#new", :as => :confirm 

       end
       resources :relationships, :only => [:create, :destroy]

       get "/venues/list" => "venues#list", :as => :venues_list

       resources :venues

       get "/events/tag/:id" => "events#tag", :as => :event_tags 
       get "/events/list" => "events#list"
       get "/events/mylist" => "events#mylist"
       get "/events/mygrid" => "events#mygrid"
       get "/events/all" => "events#index"
       
       resources :events

       resources :users, :only => [:show, :update]

       get ':id/venues' => 'users#venues', :as => :uservenues
       get ':id/events' => 'users#events', :as => :userevents
       get ':id/following' => 'users#following', :as => :following
       get ':id/followers' => 'users#followers', :as => :followers
       match ':id' => 'users#show'

  end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :authenticate_user!
   before_filter :current_user, :only => [:edit, :update]
  def account
    @user = current_user
  end

  def password
    @user = current_user
  end

  def update_password
    @user = current_user
    # raise params.inspect
    if @user.update_with_password(params[:user])
      sign_in(@user, :bypass => true)
      redirect_to root_path, :notice => "Your Password has been updated!"
    else
      render :password ,:locals => { :resource => @user, :resource_name => "user" }
    end
  end

  def deactivate_me
    @user = current_user
    # raise params.inspect
    if @user.update_attributes(params[:user])
      redirect_to root_path, :notice => "Your Account has been deactivated!"
    else
      render :password ,:locals => { :resource => @user, :resource_name => "user" }
    end
    
  end
  def notifications
    @user = User.find_by_username(current_user.username)
  end

  def profile
    @user = current_user
  end

  def avatar_upload
    @user = current_user

     respond_to do |format|
       if @user.update_attributes(params[:user])
         format.html { redirect_to "/settings/profile", notice: 'User was successfully updated.' }
       else
         format.html { render action: "profile" }
       end
     end
  end


end

app/helpers/settings_helper.rb
module SettingsHelper
    def resource_name
      :user
    end

    def resource
      @resource = current_user || User.new
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end

    def devise_error_messages!
      return "" if resource.errors.empty?

      messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
      sentence = I18n.t("errors.messages.not_saved",
                        :count => resource.errors.count,
                        :resource => resource_name)

      html = <<-HTML
			  <script type="text/javascript">
  				$.gritter.add({
  					title: "#{sentence}",
  					text: "#{messages}"
  				});
			</script>
   HTML

      html.html_safe
    end
end

app/views/settings/account.html.erb
	 <div class="twoofthree padder">
<%= form_for(@user) do |f| %>
   <article>
	    <div class="profile_text">
		 			<div class="holder">
	         <h3 class="fkey">Email</h2>
	         <div class="val"><%= f.text_field :email %></div>
	       </div>
		 			<div class="holder">
	         <h3 class="fkey">User Name</h2>
	         <div class="val"><%= f.text_field :username %></div>
	       </div>
				 <div class="holder">
		         <h3 class="fkey">Language</h2>
		         <div class="val"><%= f.text_field :language %>
		       </div> 
	       </div>
		 			<div class="holder">
	         <h3 class="fkey">Time Zone</h2>
	         <div class="val"><%= f.text_field :timezone %></div>
	       </div>
	
			 <div class="holder">
			   <h3 class="key"></h2>
        <div class="val">  <%= f.submit "UPDATE PROFILE", :class =>" button" %></div>
			  </div></div>
	 </article>
 <% end %>
	  </div>
	  <div class="oneofthree padder"> a</div>
	</div>

app/views/settings/notifications.html.erb
<script type="text/javascript" src="/javascripts/jquery.tooltips.js"></script>
<script>
$(function(){
$(".notificationTip").tipTip({defaultPosition: "top"});
});</script>
	 <div class="twoofthree padder">
   <article>
	<div id="notificationSettings" class="settingsBox">
        <div class="notifications">
        <h4>Follower Activity</h4>
        <div class="row header_row">
          <div class="column_push column"><img alt="" class="notificationTip" title="Push Notifications" src="/images/icons/32-iphone.png"></div>
          <div class="column_email column"><img alt="" class="notificationTip" title="Email Notifications" src="/images/icons/18-envelope.png"></div>
         </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When my followers check in</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When I receive a follower request or follower confirmation</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox" ></div>
          <div class="column_desc column">When a new follower from Facebook joins Gloced</div>
        </div>
      </div>
      <div class="notifications">
        <h4>Comments</h4>
        <div class="row header_row">
         <div class="column_push column"><img alt="" class="notificationTip" title="Push Notifications" src="/images/icons/32-iphone.png"></div>
          <div class="column_email column"><img alt="" class="notificationTip" title="Email Notifications" src="/images/icons/18-envelope.png"></div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When someone comments on my check-in, or replies to one of my comments</div>
        </div>
        
      </div>
      <div class="notifications">
        <h4>Tips &amp; To-Dos</h4>
        <div class="row header_row">
         <div class="column_push column"><img alt="" class="notificationTip" title="Push Notifications" src="/images/icons/32-iphone.png"></div>
          <div class="column_email column"><img alt="" class="notificationTip" title="Email Notifications" src="/images/icons/18-envelope.png"></div>
       </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When a follower does one of my Tips</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When a follower wants to go to the same place I do</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox" ></div>
          <div class="column_desc column">When a follower adds one of my Tips to their To-Do list</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When a followers shares a place, tip, or list with me</div>
        </div>
      </div>
      <div class="notifications">
        <h4>Specials</h4>
        <div class="row header_row">
         <div class="column_push column"><img alt="" class="notificationTip" title="Push Notifications" src="/images/icons/32-iphone.png"></div>
          <div class="column_email column"><img alt="" class="notificationTip" title="Email Notifications" src="/images/icons/18-envelope.png"></div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When I unlock a Special</div>
        </div>
      </div>
      <div class="notifications">
        <h4>The Game</h4>
        <div class="row header_row">
         <div class="column_push column"><img alt="" class="notificationTip" title="Push Notifications" src="/images/icons/32-iphone.png"></div>
          <div class="column_email column"><img alt="" class="notificationTip" title="Email Notifications" src="/images/icons/18-envelope.png"></div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When I unlock a badge</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">When I get ousted as Mayor</div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox" ></div>
          <div class="column_email column"><input type="checkbox" ></div>
          <div class="column_desc column">When I earn extra points</div>
        </div>
      </div>
      <div class="notifications">
        <h4>News and Updates</h4>
        <div class="row header_row">
         <div class="column_push column"><img alt="" class="notificationTip" title="Push Notifications" src="/images/icons/32-iphone.png"></div>
          <div class="column_email column"><img alt="" class="notificationTip" title="Email Notifications" src="/images/icons/18-envelope.png"></div>
        </div>
        <div class="row">
          <div class="column_push column"><input type="checkbox"></div>
          <div class="column_email column"><input type="checkbox"></div>
          <div class="column_desc column">Keep me up-to-date with Gloced news and updates</div>
        </div>
       </div>
  </div>
</article>
</div><div class="oneofthree padder">s	</div>

app/views/settings/password.html.erb
	 <div class="twoofthree padder">
  <article>
		<%= form_for(resource, :as => resource_name, :url => update_password_path, :html => { :method => :put }) do |f| %>
		  
		<%= devise_error_messages! %>

			<div class="holder">
        <h3 class="fkey"><%= f.label :current_password %></h2>
        <div class="val"><%= f.password_field :current_password %></div>
      </div>

			<div class="holder">
        <h3 class="fkey"><%= f.label :password, "New Password" %></h2>
        <div class="val"><%= f.password_field :password %></div>
      </div>
			<div class="holder">
        <h3 class="key"><%= f.label :password_confirmation %></h2>
        <div class="val"><%= f.password_field :password_confirmation %></div>
      </div>
			<div class="holder">
        <h3 class="fkey"></h2>
        <div class="val"><%= f.submit "Change Password", :class => "button"  %></div>
      </div>

			<% end %>
			 </article>  
	</div>	  
	
	
	<div class="oneofthree padder"><h3>Cancel my account</h3>

	<p>Unhappy? <%= link_to "Cancel my account", deactivate_me_path,:params => {:status => 0}, :confirm => "Are you sure?", :method => :put %>.</p>

	<%= link_to "Back", :back %>
	
	</div>

<script src="/javascripts/jquery.validate.js" type="text/javascript"></script>


<script>
$(document).ready(function(){
  $("#settings").validate({
	  rules: {
	    settings_current_password: "required",
	    settings_password: "required",
	    settings_password_confirmation: "required",
	    settings_password_confirmation: {
	      equalTo: "#edit_password"
	    }
	  }
	});
});
</script>

app/views/settings/profile.html.erb
	 <div class="twoofthree padder">
<%= form_for(@user) do |f| %>
   <article>
	    <div class="profile_text">
		 			<div class="holder">
	         <h3 class="fkey">First Name</h2>
	         <div class="val"><%= f.text_field :firstName %></div>
	       </div>
				 <div class="holder">
		         <h3 class="fkey">Last Name</h2>
		         <div class="val"><%= f.text_field :lastName %></div>
		       </div> 
		 			<div class="holder">
	         <h3 class="fkey">About</h2>
	         <div class="val"><%= f.text_field :about,:size=>"30", :maxlength=>"200"%></div>
	       </div>
		 			<div class="holder">
	         <h3 class="fkey">City</h2>
	         <div class="val"><%= f.text_field :city %></div>
	       </div>
	       <div class="holder">
	         <h3 class="fkey">Places Visited</h2>
	         <div class="val"><%= f.text_field :places %></div>
	       </div>
			 <div class="holder">
			   <h3 class="key"></h2>
        <div class="val">  <%= f.submit :class =>" button" %></div>
			  </div></div>
	 </article>
 <% end %>

	    </article>
	  </div>
		<div class="oneofthree padder">
		  <div style="width:310px; height:310px; overflow:hidden"> <%= image_tag @user.avatar.url(:medium) %> </div>
		 <%= form_for(@user, :url => '/settings/avatar_upload', :html => { :method => :put }) do |f| %>
		 <%= f.file_field :avatar %> <%= f.submit "UPDATE Avatar", :class =>" button" %>
		  <% end %>
		</div>